### ISSUE TITLE
Questions about the type of cells used in the dataset

### ISSUE THREAD

**Issue by xhxlab** [TengMichael/battery-charging-data-of-on-road-electric-vehicles#1]
I have noticed that the voltage range of the cell is approximately between 3.6V to 4.2V. May I know if my assumption that this battery is a ternary lithium battery is correct? I would appreciate your guidance.

**Comment by TengMichael** [comment]
Yes, the type of battery is a ternary lithium battery.


Zhongwei Deng    Associate Professor
School of Mechanical and Electrical Engineering,
University of Electronic Science and Technology of China, 
No.2006, Xiyuan Ave, West Hi-Tech Zone, Chengdu, 611731, China
E-mail: ***@***.***; ***@***.***
https://scholar.google.com.hk/citations?user=aL1sCI4AAAAJ&hl=zh-EN
https://faculty.uestc.edu.cn/dengzhongwei
 
From: xhxlab
Date: 2023-05-30 11:00
To: TengMichael/battery-charging-data-of-on-road-electric-vehicles
CC: Subscribed
Subject: [TengMichael/battery-charging-data-of-on-road-electric-vehicles] Questions about the type of cells used in the dataset (Issue #1)
I have noticed that the voltage range of the cell is approximately between 3.6V to 4.2V. May I know if my assumption that this battery is a ternary lithium battery is correct? I would appreciate your guidance.

**Comment by wxt521-520** [comment]
老师，你好，这个三元锂电池类型是NCA类型还是NCM类型，麻烦老师告知一下
