### ISSUE TITLE
不清楚论文图二中电池1的最低容量115是如何计算到的

### ISSUE THREAD

**Issue by ditan5678** [TengMichael/battery-charging-data-of-on-road-electric-vehicles#2]
2021年11月SOC到95以上的容量也有124Ah，可以详细介绍一下115Ah是按什么标准计算出来的吗，或者开源一下数据处理部分的计算源码

**Comment by TengMichael** [comment]
利用安时积分公式变换（公式1），可以根据1个充电片段计算出一个容量点，
对每个月内计算的容量点，统计其均值或中位值，可以得到图中所示结果。


Zhongwei Deng    Associate Professor
School of Mechanical and Electrical Engineering,
University of Electronic Science and Technology of China, 
No.2006, Xiyuan Ave, West Hi-Tech Zone, Chengdu, 611731, China
E-mail: ***@***.***; ***@***.***
https://scholar.google.com.hk/citations?user=aL1sCI4AAAAJ&hl=zh-EN
https://faculty.uestc.edu.cn/dengzhongwei
 
发件人： pruse
发送时间： 2023-06-18 19:30
收件人： TengMichael/battery-charging-data-of-on-road-electric-vehicles
抄送： Subscribed
主题： [TengMichael/battery-charging-data-of-on-road-electric-vehicles] 不清楚论文图二中电池1的最低容量115是如何计算到的 (Issue #2)
2021年11月SOC到95以上的容量也有124Ah，可以详细介绍一下115Ah是按什么标准计算出来的吗，或者开源一下数据处理部分的计算源码

**Comment by ditan5678** [comment]
感谢老师的回复，还有一个问题，数据里available_capacity (Ah)一列是通过您说的安时积分计算出来的吗

**Comment by TengMichael** [comment]
不是的，那个是BMS上报的，可以不用管。

**Comment by whitecontry** [comment]
请问能具体讲一下充电片段的选取吗 目前计算出来展示不出来您论文中的退化趋势

**Comment by TengMichael** [comment]
容量提取代码已上传
