### ISSUE TITLE
电池额定容量

### ISSUE THREAD

**Issue by xhxlab** [TengMichael/battery-charging-data-of-on-road-electric-vehicles#4]
请问这些汽车电池PACK的额定容量是多少安时？

**Comment by TengMichael** [comment]
145Ah



Zhongwei Deng    Associate Professor
School of Mechanical and Electrical Engineering,
University of Electronic Science and Technology of China, 
No.2006, Xiyuan Ave, West Hi-Tech Zone, Chengdu, 611731, China
E-mail: ***@***.***; ***@***.***
https://scholar.google.com.hk/citations?user=aL1sCI4AAAAJ&hl=zh-EN
https://faculty.uestc.edu.cn/dengzhongwei
 
发件人： xhxlab
发送时间： 2023-06-28 16:49
收件人： TengMichael/battery-charging-data-of-on-road-electric-vehicles
抄送： Subscribed
主题： [TengMichael/battery-charging-data-of-on-road-electric-vehicles] 电池额定容量 (Issue #4)
请问这些汽车电池的额定容量是多少安时？
