### ISSUE TITLE
能否将已经处理的容量数据或校正SOC数据公开呢

### ISSUE THREAD

**Issue by YEEUrl** [TengMichael/battery-charging-data-of-on-road-electric-vehicles#6]
按照您的方法对其中的数据进行处理，但是因为没有相对应的可供判断的数据，作者这边提供的是每月的平均值，无法判断对某一日的容量估计是否准确。希望能够得到您的帮助，感谢！

**Comment by TengMichael** [comment]
电池的容量本身就会随工况和温度的变化而波动，因此，不建议按照某日的容量来进行判断。按照月平均来分析，更具有实际价值。
当然，如果你的模型输入为单日数据特征，可以提取单日的容量进行评估。



Zhongwei Deng    Associate Professor
School of Mechanical and Electrical Engineering,
University of Electronic Science and Technology of China, 
No.2006, Xiyuan Ave, West Hi-Tech Zone, Chengdu, 611731, China
E-mail: ***@***.***; ***@***.***
https://scholar.google.com.hk/citations?user=aL1sCI4AAAAJ&hl=zh-EN
https://faculty.uestc.edu.cn/dengzhongwei
 
发件人： YEEUrl
发送时间： 2023-12-20 11:51
收件人： TengMichael/battery-charging-data-of-on-road-electric-vehicles
抄送： Subscribed
主题： [TengMichael/battery-charging-data-of-on-road-electric-vehicles] 能否将已经处理的容量数据或校正SOC数据开源呢 (Issue #6)
按照您的方法对其中的数据进行处理，但是因为没有相对应的可供判断的数据，作者这边提供的是每月的平均值，无法判断对某一日的容量估计是否准确。希望能够得到您的帮助，感谢！

**Comment by wxt521-520** [comment]
你好，处理数据集容量的代码可以公开一下吗

**Comment by YEEUrl** [comment]
请问您对于数据集容量进行处理的代码或者预处理过后容量代码能否更新一下呢。

**Comment by TengMichael** [comment]
容量提取代码已上传。
