### ISSUE TITLE
电池的容量本身就会随工况和温度的变化而波动，因此，不建议按照某日的容量来进行判断。按照月平均来分析，更具有实际价值。

### ISSUE THREAD

**Issue by gitjinbo** [TengMichael/battery-charging-data-of-on-road-electric-vehicles#7]
电池的容量本身就会随工况和温度的变化而波动，因此，不建议按照某日的容量来进行判断。按照月平均来分析，更具有实际价值。
当然，如果你的模型输入为单日数据特征，可以提取单日的容量进行评估。

Zhongwei Deng    Associate Professor
School of Mechanical and Electrical Engineering,
University of Electronic Science and Technology of China, 
No.2006, Xiyuan Ave, West Hi-Tech Zone, Chengdu, 611731, China
E-mail: ***@***.***; ***@***.***
https://scholar.google.com.hk/citations?user=aL1sCI4AAAAJ&hl=zh-EN
https://faculty.uestc.edu.cn/dengzhongwei
 
发件人： YEEUrl
发送时间： 2023-12-20 11:51
收件人： TengMichael/battery-charging-data-of-on-road-electric-vehicles
抄送： Subscribed
主题： [TengMichael/battery-charging-data-of-on-road-electric-vehicles] 能否将已经处理的容量数据或校正SOC数据开源呢 (Issue #6)
按照您的方法对其中的数据进行处理，但是因为没有相对应的可供判断的数据，作者这边提供的是每月的平均值，无法判断对某一日的容量估计是否准确。希望能够得到您的帮助，感谢！
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

_Originally posted by @TengMichael in https://github.com/TengMichael/battery-charging-data-of-on-road-electric-vehicles/issues/6#issuecomment-1863886751_

**Comment by gitjinbo** [comment]
您好！我按照您的方法进行了对数据的预处理，大致一个csv文件有1400个左右的循环，我是直接以charge cycles为x轴，capacity为y轴，绘制的图像确实是规律不太明显，波动非常大。但如果按照您这种以月进行平均这种思路来考量，我直接算的是30个充电次数的capacity的均值，发现数据量变少的同时，也没能有一个比较明显的效果，求解惑?

**Comment by TengMichael** [comment]
容量提取代码已上传。
